### ISSUE TITLE
port_filter.py

### ISSUE THREAD

**Issue by cdaly2** [brenns10/pywall#42]
Hello.
On line 32 of the filter_condition method is the code

        match = (packet.get_protocol() == self._protocol)
        match = (packet.get_payload() is not None)

The second assignment splatts the first one and I am wondering if it isn't meant to be
        match = (packet.get_protocol() == self._protocol)
        match = match and (packet.get_payload() is not None)

Thank You

**Comment by brenns10** [comment]
You are correct. Looking through the history, there was a bad [merge](https://github.com/brenns10/pywall/commit/5f1ded887a49374bd03dadf50b612de5f1d15c56) which overwrote changes in a [commit](https://github.com/brenns10/pywall/commit/6f35dfea890575ff90f5d4c606f0d1ff8e0eeceb#diff-0723b2316b580f135292b3d0c957faebba50f589c79bc454332c460b09bd0124) after the branch had diverged.

Ultimately this is a course project which is not maintained -- I haven't actually even tried to run it it years. If you'd like to submit a PR clearing up the issue, I'd accept it, to prevent future viewers from encountering the issue. But if you intend to keep working with any of this code in the long term, I'd encourage a friendly fork :)

**Comment by cdaly2** [comment]
OK, thanks. I friendly forked it :)

I think I did a PR (I'm new to githib and amn't sure I did it right).

**Comment by brenns10** [comment]
You did it correctly! I went ahead and merged it.

Feel free to open issues if you have any questions about the code and I'll try to answer them. It has been a while since we wrote this code, but I'll do my best. Reading old code is fun :)

From here on out though, I don't think we'll be accepting pull requests in the repo in general as it is not an active project. Enjoy working on your fork though!
